language: node_js
node_js:
- "12"
notifications:
  email: false


script:
  - cd ./auth && yarn install && yarn test
  - cd ..
  - cd ./tickets && yarn install && yarn test
  - cd ..
  - cd ./orders && yarn install && yarn test
