apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  local:
    #push: false
  googleCloudBuild:
    projectId: fit-reference-296121
  artifacts:
    - image: gcr.io/fit-reference-296121/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*/src/**/*.ts'
            dest: .
    - image: gcr.io/fit-reference-296121/ticketingclient
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: gcr.io/fit-reference-296121/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*/src/**/*.ts'
            dest: .
    - image: gcr.io/fit-reference-296121/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*/src/**/*.ts'
            dest: .
    - image: gcr.io/fit-reference-296121/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*/src/**/*.ts'
            dest: .
    - image: gcr.io/fit-reference-296121/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*/src/**/*.ts'
            dest: .
